hidaxphoenix/freemarket_sample_70c

README.md
=> DB_setting

README.md
DB設計
提出ミスがあったため、再度作成 
https://gyazo.com/387d3250a6340782e55b3b10e5654838
=> DB_setting2

app/assets/stylesheets/_items_new.scss, app/assets/stylesheets/application.scss, app/controllers/items_controller.rb, app/views/items/new.html.haml, config/routes.rb
=> base-view-setting

Gemfile, Gemfile.lock, README.md, app/assets/javascripts/users.coffee, app/assets/stylesheets/_devise.scss, app/assets/stylesheets/users.scss, app/controllers/application_controller.rb, app/controllers/users_controller.rb, app/helpers/users_helper.rb, app/models/user.rb, app/views/devise/passwords/new.html.haml, app/views/devise/registrations/new.html.haml, app/views/devise/sessions/new.html.haml, app/views/devise/shared/_links.html.haml, app/views/items/index.html.haml, config/application.rb, config/initializers/devise.rb, config/locales/devise.views.ja.yml, db/migrate/20200304120231_devise_create_users.rb, db/schema.rb, test/controllers/users_controller_test.rb
#What
ユーザー新規登録/ログインページのマークアップ
#Why
ユーザーの方が、登録等でストレスが無いようにビューを整えた。
=> user_mark_up

app/assets/stylesheets/_items_new.scss, app/views/items/new.html.haml, app/views/layouts/application.html.haml
出品ページ作成
出品する必要があり、そのページが必要だから
1.
https://gyazo.com/ba78ac6141c85a8ee59d89e06dc87c5a
2.
https://gyazo.com/07f697024030eb9dc01167aaef89b58f
3.
https://gyazo.com/8694fc0a8533bfbf0142b9bb484f8df4
=> View item new

README.md, app/models/item.rb, db/migrate/20200306075133_create_items.rb, db/schema.rb, test/fixtures/items.yml, test/models/item_test.rb
=> setting_db_items

README.md, app/models/brand.rb, db/migrate/20200306121153_create_brands.rb, db/schema.rb, test/fixtures/brands.yml, test/models/brand_test.rb
brandのテーブル作成
#Why
各パスを通すのに必須のテーブルなので作成しました。
=> brand_db_setting

app/models/condition.rb, db/migrate/20200306123203_create_conditions.rb, db/schema.rb, test/fixtures/conditions.yml, test/models/condition_test.rb
conditionテーブルの作成
itemに必須の情報なので作成しました。
=> condition_db_setting

app/assets/stylesheets/_items_index.scss, app/views/items/index.html.haml
index_view_image修正
デプロイ時の画像表示のため
=> index_view_image　修正

app/assets/stylesheets/_items_confirm.scss, app/views/items/confirm.html.haml
=> add_view_items_confirm

app/views/devise/shared/_links.html.haml, app/views/items/_footer.html.haml, app/views/items/_header.html.haml, app/views/items/new.html.haml, app/views/items/show.html.haml
items/show&new    users/new&log_in  のimage_tagとlink_toにclass付け替え
デプロイで画像を表示させるため
=> image_tag & add_link_to_class

app/assets/stylesheets/_items_index.scss
=> fix_index_view

app/assets/stylesheets/_items_confirm.scss, app/assets/stylesheets/_items_new.scss, app/views/items/confirm.html.haml, app/views/items/new.html.haml
viewの編集
viewのclassの名前の被りを修正、heaer,footerのrenderで部分テンプレート化
=> fix_view_new&confirm

app/assets/stylesheets/_items_confirm.scss, app/views/items/confirm.html.haml
=> add_items_confirm_view

app/views/items/show.html.haml
view_items_showのimgをimage_tagに変更。
本番環境で画像を表示させるため。
=> fix_imagetag_view_items_show

app/assets/stylesheets/_items_index.scss, app/assets/stylesheets/_users.scss, app/views/items/_index-header.html.haml, app/views/users/index.html.haml
ログインしている時のヘッダーのビュー崩れを直しました。
ビューが崩れて、すごく見ずらかったため。
=> ログインした時してない時のヘッダーの表示

app/controllers/items_controller.rb, app/controllers/users_controller.rb
#What
各ビューに飛ぶためのコントローラ作成
#Why
チームメンバーが、スムーズに作業するため
=> contoller_setting

app/assets/stylesheets/_devise.scss, app/assets/stylesheets/_users.scss, app/views/devise/registrations/create_address.html.haml, app/views/items/_index-header.html.haml, app/views/users/index.html.haml, config/routes.rb
#What
ユーザー登録画面のビューの修正
#Why
ユーザーの方がより使いやすくなるため
=> Completion_of_registration

app/assets/javascripts/new_item.js, app/assets/stylesheets/_items_new.scss, app/controllers/items_controller.rb, app/models/item.rb, app/views/items/new.html.haml
出品ページの画像投稿に複数枚投稿機能の追加。
購入者により多くの商品情報を伝えるため。
=> fix_imageposting_number

app/assets/javascripts/new_item.js, app/assets/stylesheets/_items_new.scss
画像の複数枚投稿機能の実装
5まいごとに挿入欄が下にずれる
10枚で挿入欄が消えるように修正
画像を複数枚投稿できるようにすることでユーザーが使いやすいようにする。
その際のビューを見やすいようにしました。
=> photo-many-function

app/assets/javascripts/counter.js, app/assets/stylesheets/_items_new.scss, app/views/items/new.html.haml
=> Writing counter

app/assets/stylesheets/_items_new.scss, app/assets/stylesheets/application.scss, app/views/items/edit.html.haml
編集用ページ作成　出品用ページのSCSSを修正
編集作業にviewが必要なので作成しました。
出品用ページに関してはビュー崩れ起こしている部分があったので修正しました。
=> create_edit_view & fix_new_view_scss

app/controllers/items_controller.rb, app/views/items/new.html.haml
=> fix_items_new_link

app/assets/javascripts/application.js
tarbolinksを削除
tarbolinksが邪魔をしていたため
=> change_setting_tarbolinks

app/assets/stylesheets/_items_new.scss
=> exihibition_view_fix

README.md, app/assets/javascripts/condition.js, app/controllers/items_controller.rb, app/models/condition.rb, app/models/item.rb, app/views/items/new.html.haml, db/migrate/20200313075111_condition_toitems.rb, db/schema.rb
出品機能に"商品状態"の選択肢を追加
出品時に必須の機能なので
=> add_condition_function

app/assets/stylesheets/_items_index.scss, app/views/items/_index-header.html.haml
index_viewのheaderを修正
ずれて表示されていたので
=> fix_index_header

app/assets/stylesheets/_items_index.scss
item_indexの商品一覧が縦表示になっていたので、横表示に修正しました。
見やすい表示にするため
=> fix_index_view_itembox

app/assets/stylesheets/_items_show.scss, app/controllers/items_controller.rb, app/views/items/edit.html.haml, app/views/items/new.html.haml, app/views/items/show.html.haml
#What 
商品に編集・削除機能を実装。
#Why
ユーザーさんが出品したものを編集・削除できるよう。
=> edit_destroy_setting

app/views/users/index.html.haml
#What
ユーザーマイページに名前表記
#Why
これまで仮置きだったマイページの名前を修正
=> add_user_mypage

app/controllers/items_controller.rb
=> fix_edit_function

app/assets/stylesheets/_items_show.scss, app/uploaders/image_uploader.rb, app/views/items/show.html.haml
item_showのimage画像表示の修正
購入者が見やすくするため
=> fix_item_show_view_image

app/models/item.rb, app/models/user.rb, app/views/items/edit.html.haml, db/migrate/20200316103833_add_saler_id_to_item.rb, db/migrate/20200316104003_add_buyer_id_to_item.rb, db/schema.rb
#What
buyer,salerのidカラムを作成。
#Why
購入者と出品者を分ける
=> buyer_saler_setting

app/assets/javascripts/category.js, app/assets/javascripts/category_edit.js, app/controllers/items_controller.rb, app/views/items/edit.html.haml, config/routes.rb
商品編集機能にカテゴリ機能を追加
カテゴリを変更する必要があるため
=> Fix edit function

app/assets/javascripts/comments.coffee, app/assets/javascripts/items.coffee, app/assets/javascripts/users.coffee, app/assets/stylesheets/_items_show.scss, app/assets/stylesheets/comments.scss, app/controllers/comments_controller.rb, app/controllers/items_controller.rb, app/helpers/comments_helper.rb, app/models/comment.rb, app/models/item.rb, app/models/user.rb, app/views/items/show.html.haml, config/routes.rb, db/migrate/20200317032709_create_comments.rb, db/schema.rb, spec/controllers/comments_controller_spec.rb, spec/factories/comments.rb, spec/helpers/comments_helper_spec.rb, spec/models/comment_spec.rb
#What
コメント機能の実装。
#Why
ユーザーさんが、アイテムに対してコメントできるように。
=> comment_setting

app/views/items/edit.html.haml
孫カテゴリーを変えずに出品できるように
孫カテゴリーを変えずに出品できるようにするため
=> fix_edit_category

app/views/items/done.html.haml
リンクをitemからdoneに通す
doneから戻れるようにするため
=> add_link_item_done

app/controllers/items_controller.rb, app/views/items/index.html.haml
itemのindexページにて、購入済みの商品を出せないようにする
#why
itemのindexページにて、購入済みの商品を出せないようにするため
=> item_index_view_finishedsold

app/controllers/items_controller.rb
購入機能の支払い金額が固定されていたのでitemの金額と同期させる
購入金額が固定されていなかったので、変更した
=> add_fix_payjp_price

app/assets/stylesheets/_cards_new.scss, app/assets/stylesheets/_cards_show.scss, app/views/card/show.html.haml
=> card-showpage-view

app/assets/javascripts/application.js, app/assets/javascripts/new_item.js, app/assets/stylesheets/_items_new.scss, app/controllers/items_controller.rb, app/views/items/edit.html.haml, app/views/items/new.html.haml, app/views/layouts/application.html.haml
画像複数投稿と複数編集機能を追加
必須機能なので実装しました。
=> fix_item_new_image_doing

app/assets/stylesheets/_items_index.scss, app/controllers/items_controller.rb, app/models/item.rb, app/views/items/_index-header.html.haml, app/views/items/search.html.haml, config/routes.rb
曖昧検索を実装
検索機能をつけることにより、より使いやすくなるため
=> add_search_function

Gemfile, Gemfile.lock
gem ransackの導入
ransackを使った、検索機能導入のため
=> add_gem_ransack

app/assets/javascripts/likes.coffee, app/assets/stylesheets/likes.scss, app/controllers/items_controller.rb, app/controllers/likes_controller.rb, app/helpers/likes_helper.rb, app/models/item.rb, app/models/like.rb, app/models/user.rb, app/views/items/show.html.haml, app/views/likes/_like.html.haml, app/views/likes/create.js.haml, app/views/likes/destroy.js.haml, config/initializers/devise.rb, config/locales/devise.views.ja.yml, config/routes.rb, db/migrate/20200318013510_create_likes.rb, db/migrate/20200318094459_add_clomun_to_likes.rb, db/schema.rb, spec/controllers/likes_controller_spec.rb, spec/factories/likes.rb, spec/helpers/likes_helper_spec.rb, spec/models/like_spec.rb
#What
いいね機能の実装
#Why
ユーザーさんが、お気に入りにいいね押せるため。
=> add_like_setting

Gemfile, Gemfile.lock, app/controllers/items_controller.rb, app/models/item.rb, app/views/items/search.html.haml, config/routes.rb
=> add_detile_search_function

app/assets/javascripts/new_item.js, app/assets/stylesheets/_cards_new.scss, app/assets/stylesheets/_items_new.scss, app/views/items/new.html.haml
=> Fix item new image post

app/views/items/edit.html.haml, app/views/items/new.html.haml
=> fix_edit_image

app/controllers/comments_controller.rb, app/views/items/show.html.haml
コメント機能修正（コメント投稿後のパス、投稿コメントの表示）
コメント投稿後のパスが、別商品のshowを表示していたので修正しました。
=> fix_comment_function

app/assets/stylesheets/_items_show.scss, app/views/items/show.html.haml
=> item-comment-view-fix

app/controllers/items_controller.rb, app/views/items/edit.html.haml
商品編集ページのカテゴリの初期値修正
#why
初期値が正しくなかったため
=> fix_edit_item_view_category

app/assets/stylesheets/_done.scss, app/assets/stylesheets/application.scss, app/controllers/items_controller.rb, app/controllers/likes_controller.rb, app/models/item.rb, app/models/like.rb, app/models/user.rb, app/views/items/done.html.haml, app/views/likes/_like.html.haml, app/views/likes/create.js.haml, app/views/likes/destroy.js.haml, app/views/likes/like.js.haml, app/views/likes/unlike.js.haml, config/routes.rb
#What
いいね機能の修正
#Why
非同期がうまくいってなかったため
=> like_setting

app/assets/javascripts/new_item.js, app/assets/stylesheets/_items_index.scss, app/assets/stylesheets/_items_new.scss, app/controllers/items_controller.rb, app/views/items/_index-header.html.haml, app/views/items/edit.html.haml, app/views/items/new.html.haml, app/views/items/show.html.haml
=> fix_edit_image_function

app/views/items/show.html.haml, app/views/likes/_like.html.haml
viewの_Likeとitems_showを修正
未ログイン時のNomethod errorを修正のため。
=> fix_like&show
